<?php
require '../www/protected/models/ContactForm.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-11 at 19:45:11.
 */
class ContactFormTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ContactForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ContactForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ContactForm::rules
     * @todo   Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
                $this->assertTrue(TRUE);
    }

    /**
     * @covers ContactForm::attributeLabels
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
